return {
	"scottmckendry/cyberdream.nvim",
	lazy = false,
	priority = 1000,
	opts = {
		cache = true,
		extensions = {
			alpha = false,
			blinkcmp = true,
			cmp = false,
			dapui = false,
			dashboard = false,
			fzflua = false,
			gitpad = false,
			gitsigns = true,
			grapple = false,
			grugfar = false,
			heirline = true,
			helpview = false,
			hop = false,
			indentblankline = false,
			kubectl = false,
			lazy = true,
			leap = false,
			markdown = true,
			markview = true,
			mini = true,
			neogit = true,
			noice = true,
			notify = true,
			rainbow_delimiters = false,
			snacks = true,
			telescope = true,
			treesitter = true,
			treesittercontext = false,
			trouble = false,
			whichkey = true,
		},
	},
}
