return {
	"scottmckendry/cyberdream.nvim",
	lazy = false,
	priority = 1000,
	opts = {
		extensions = {
			default = false,
			blinkcmp = true,
			dapui = true,
			fzflua = true,
			gitsigns = true,
			grapple = true,
			heirline = true,
			lazy = true,
			markview = true,
			mini = true,
			neogit = true,
			noice = true,
			snacks = true,
			telescope = true,
			treesitter = true,
			whichkey = true,
		},

		transparent = true,
		cache = true,
		italic_comments = true,
		-- hide_fillchars = true,
		-- borderless_pickers = true,
		-- terminal_colors = true,
		--ß highlights = {},
		-- colors = {},
	},
}
